### ISSUE TITLE
JS in static not work

### ISSUE THREAD

**Issue by Chhunneng** [mirumee/legacy-views#32]
### What I'm trying to achieve
I want JS file is working. I add more code to navbar.js but it is not showing the console when run.

### Steps to reproduce the problem
I want to change navbar in phone.

### What I expected to happen
I test for the console in navbar.js but in a web no console happened.

### Screenshots

**System information**
Operating system: 
Browser:

**Comment by NyanKiyoshi** [comment]
Hi!

Did you try rebuilding the assets?

When developing, you can use `npm start` to automatically recompile your changes.

**Comment by Chhunneng** [comment]
Thank so much!
